config/routes.rb
Rails.application.routes.draw do
  resources :movies, :movie_pages, :movie_actions

end

app/controllers/movie_actions_controller.rb
class MovieActionsController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  caches_action :index, :show, expires_in: 20.seconds

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
    fresh_when last_modified: @movies.max(:updated_at)
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
#    headers["ETag"]=Digest::MD5.hexdigest(@movie.cache_key) 
#    headers["Last-Modified"]=@movie.updated_at.httpdate
#    fresh_when(@movie)
    @movie.movie_accesses.create(:action=>"cached-action#show")
    if stale? @movie
      @movie.movie_accesses.create(:action=>"cached-action#show-stale")
      #do some additional, expensive work here

      secs=10
      response.headers["Expires"] = secs.seconds.from_now.httpdate
#     response.headers["Cache-Control"] = "public, max-age=#{secs}"
      expires_in secs.seconds, :public=>true
    end
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        fresh_when(@movie)
        @movie.movie_accesses.create(:action=>"cached-action#create")
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        expire_action action: "show", id:@movie, format: request.format.symbol
        expire_action action: "index", format: request.format.symbol
        fresh_when(@movie)
        @movie.movie_accesses.create(:action=>"cached-action#update")
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.movie_accesses.create(:action=>"cached-action#destroy")
    @movie.destroy
    expire_action action: "show", id:@movie, format: request.format.symbol
    expire_action action: "index", format: request.format.symbol
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:id, :title, :updated_at)
    end
end

app/helpers/movie_actions_helper.rb
module MovieActionsHelper
end

app/views/movie_actions/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie_action from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movie_actions/edit.html.erb
<h1>Editing Movie Action</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movie_actions_path %>

app/views/movie_actions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Movie Actions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie_action| %>
      <tr>
        <td><%= movie_action.title %></td>
        <td><%= link_to 'Show', movie_action %></td>
        <td><%= link_to 'Edit', edit_movie_action_path(movie_action) %></td>
        <td><%= link_to 'Destroy', movie_action, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie action', new_movie_action_path %>

app/views/movie_actions/new.html.erb
<h1>New Movie Action</h1>

<%= render 'form' %>

<%= link_to 'Back', movie_actions_path %>

app/views/movie_actions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<%= link_to 'Edit', edit_movie_action_path(@movie) %> |
<%= link_to 'Back', movie_actions_path %>